- name: Configure VM servers
  hosts: all
  become: true
  roles:
    - setup_vm

- name: Configure proxy server
  hosts: proxy_server
  become: true
  roles:
    - nginx_proxy

- name: Configure web servers
  hosts: web_servers
  become: true
  roles:
    - nginx_web
